server:
  port: 8083
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
  servlet:
    context-path: /

spring:
  application:
    name: demo-springdata
    # 设置静态文件路径，js,css等
    mvc:
      static-path-pattern: /static/**
    http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true
      multipart:
        maxFileSize: 100Mb
        maxRequestSize: 100Mb

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.201:3306/swaggertest
    username: root
    password: dsdb@1
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  # 配置freemarker
  freemarker:
    # 设置模板后缀名
    suffix: .html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    # 设置ftl文件路径 如果控制器中有 views路径 此处不需要再次添加
    template-loader-path: classpath:/templates
    # 设置静态文件路径，js,css等